services:
  - type: web
    name: denngay-bot
    runtime: python
    buildCommand: pip install -r bot/requirements.txt
    startCommand: python bot/bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Nhập thủ công khi bấm deploy để bảo mật
      - key: TELEGRAM_CHAT_ID
        value: "1389109644" # ID chat công khai được điền sẵn
